# Generated by Django 4.2.7 on 2023-11-07 15:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_project_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribeapp', '0002_rename_user_subscription_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'project')},
        ),
    ]
