# Generated by Django 4.2.7 on 2023-11-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='write',
            new_name='writer',
        ),
    ]
